In [ ]:
# prueba indexador con una consulta de ejemplo
import pandas as pd
import sys
sys.path.append('../')

from src.indexar import IndiceInvertido

# muestra pequeña para no saturar la memoria
corpus_path = '../data/processed/corpus_limpio.csv'
df = pd.read_csv(corpus_path).fillna('')

indexador = IndiceInvertido()
indexador.construir_desde_dataframe(df)

Vocabulario total: 57057 palabras únicas.

In [5]:

query = "ingeniero de datos con python"

tokens_consulta = indexador.nlp.tokenizar(query)
print(f"Consulta procesada (Stemming + Stopwords): {tokens_consulta}\n")

Consulta procesada (Stemming + Stopwords): ['ingenier', 'dat', 'python']

In [9]:
for token in tokens_consulta:
    if token in indexador.indice:
        docs = indexador.indice[token]
        print(f"El token '{token}' aparece en {len(docs)} documentos. Aquí el Top 5:")

        docs_ordenados = sorted(docs.items(), key=lambda x: x[1], reverse=True)
        
        top_doc_ids = [doc_id for doc_id, freq in docs_ordenados[:5]]
        
        df_resultados = df[df['job_id'].isin(top_doc_ids)].copy()
        
        df_resultados['Frecuencia Absoluta'] = df_resultados['job_id'].map(docs)
        
        df_resultados = df_resultados.sort_values(by='Frecuencia Absoluta', ascending=False)
        
        df_resultados = df_resultados.drop_duplicates(subset=['job_id'])
        
        columnas_legibles = ['job_title', 'company', 'location_final', 'Frecuencia Absoluta']
        columnas_legibles = [col for col in columnas_legibles if col in df_resultados.columns]
        
        display(df_resultados[columnas_legibles])
        
    else:
        print(f"El token '{token}' no se encontró en el corpus.")

El token 'ingenier' aparece en 6542 documentos. Aquí el Top 5:

                                             job_title  Frecuencia Absoluta
4762   ingeniero de producto ingeniero de aplicaciones                   56
48260           ingeniero civil de calculo estructural                   48
40439  ingeniero de producto ingeniero de aplicaciones                   46
2349   ingeniero a de proyecto de construccin elctrico                   44
2219                            ingeniero de proyectos                   39

El token 'dat' aparece en 10879 documentos. Aquí el Top 5:

                                               job_title  Frecuencia Absoluta
10515                          ingeniero de datos senior                   77
47434  geospatial data scientist machine learning eng...                   60
22601                          ingeniero de datos senior                   59
30497                                arquitecto de datos                   58
28181                                 ingeniero de datos                   54

El token 'python' aparece en 2147 documentos. Aquí el Top 5:

                                               job_title  Frecuencia Absoluta
4831                            software engineer python                   22
6356             coach para python para ciencia de datos                   11
61002  developpeur experimente en python projet sur u...                    9
10559                ingeniero de datos de python remoto                    7
64752          python software engineer any visa is fine                    7