In [1]:
# prueba indexador con una consulta de ejemplo
import pandas as pd
import sys
sys.path.append('../')

from src.indexar import IndiceInvertido

# muestra pequeña para no saturar la memoria
corpus_path = '../data/processed/corpus_limpio.csv'
df = pd.read_csv(corpus_path).fillna('')

indexador = IndiceInvertido()
indexador.construir_desde_dataframe(df)

query = "ingeniero administracion de empresas"

tokens_consulta = indexador.nlp.tokenizar(query)
print(f"Consulta procesada (Stemming + Stopwords): {tokens_consulta}\n")

Vocabulario total: 57057 palabras únicas.
Consulta procesada (Stemming + Stopwords): ['ingenier', 'administr', 'empres']

In [2]:
for token in tokens_consulta:
    if token in indexador.indice:
        docs = indexador.indice[token] 
        print(f"El token '{token}' aparece en {len(docs)} documentos. Aquí el Top 5:")
        
        top_doc_ids = list(docs.keys())[:5]
        df_resultados = df[df['job_id'].isin(top_doc_ids)].copy()
        
        #  "frecuencia" matemática sacada del índice
        df_resultados['Frecuencia Absoluta'] = df_resultados['job_id'].map(docs)
        
        # ordenar de mayor a menor frecuencia
        df_resultados = df_resultados.sort_values(by='Frecuencia Absoluta', ascending=False)
        
        columnas_legibles = ['job_title', 'company', 'location_final', 'Frecuencia Absoluta']
        columnas_legibles = [col for col in columnas_legibles if col in df_resultados.columns]
        
        display(df_resultados[columnas_legibles])
        
    else:
        print(f"El token '{token}' no se encontró en el corpus.")

El token 'ingenier' aparece en 6542 documentos. Aquí el Top 5:

                                              job_title  Frecuencia Absoluta
273     ingeniero de producto ingeniero de aplicaciones                    8
8434    ingeniero de producto ingeniero de aplicaciones                    8
19    practica tecnico o ingeniero en administracion...                    2
258                               ingeniero de servicio                    2
48    tecnico o ingeniero en administracion de empresas                    2
7975                              ingeniero de servicio                    2
1          docente jp administracion de empresas tumbes                    1

El token 'administr' aparece en 9423 documentos. Aquí el Top 5:

                                           job_title  Frecuencia Absoluta
4  ver oferta administracion de empresas auxiliar...                    8
1       docente jp administracion de empresas tumbes                    7
0  asistente de administracion y gerencia experie...                    5
3  aprendiz universitario administracion de empresas                    5
2  aprendiz universitario administracion de empre...                    2

El token 'empres' aparece en 12703 documentos. Aquí el Top 5:

                                           job_title  Frecuencia Absoluta
4  ver oferta administracion de empresas auxiliar...                    7
3  aprendiz universitario administracion de empresas                    5
0  asistente de administracion y gerencia experie...                    4
2  aprendiz universitario administracion de empre...                    2
1       docente jp administracion de empresas tumbes                    1